---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _dentists
  label: Μέλη του Ο.Σ.Τ
  create: all
  match: "**/*"
  templates:
  - members
- type: document
  path: _data/ds.yaml
  label: Μέλη Δ.Σ.
- type: directory
  path: _news
  label: Νέα
  create: all
  match: "**/*"
  templates:
  - new-general-post
- type: directory
  path: _aggelies
  label: Αγγελίες
  create: all
  match: "**/*"
  templates:
  - new-general-post
- type: directory
  path: _insurance
  label: Ασφάλιση
  create: all
  match: "**/*"
  templates:
  - new-general-post
- type: directory
  path: _supportingdocuments
  label: Δικαιολογητικά
  create: all
  match: "**/*"
  templates:
  - new-general-post
- type: directory
  path: _events
  label: Εκδηλώσεις
  create: all
  match: "**/*"
  templates:
  - new-events-post
- type: directory
  path: _laws
  label: Νομοθεσία
  create: all
  match: "**/*"
  templates:
  - new-general-post
- type: document
  path: _data/useful_links.yaml
  label: Χρήσιμοι σύνδεσμοι
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
